services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  websocket-chat-db:
    image: postgres:17.2-alpine3.21
    container_name: websocket-chat-db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: websocket_chat_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -u admin" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: