services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      HOSTNAME: ${HOSTNAME}
      KC_HOSTNAME: ${KC_HOSTNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
    ports:
      - 8080:8080
      - 5005:5005

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081

  websocket-chat-db:
    image: postgres:17.2-alpine3.21
    container_name: websocket-chat-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_MULTIPLE_DATABASES: websocket_chat_db,keycloak,nginx
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -u admin" ]
      interval: 1s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/keycloak
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - 8082:8080
    depends_on:
      - websocket-chat-db
    restart: always

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_POSTGRES_HOST: 'websocket-chat-db'
      DB_POSTGRES_PORT: ${DB_PORT}
      DB_POSTGRES_USER: ${DB_USER}
      DB_POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_POSTGRES_NAME: 'nginx'
    volumes:
      - ./nginx:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - websocket-chat-db

volumes:
  pgdata: