spring.application.name=websocket-chat
production.environment=${PRODUCTION_ENVIRONMENT:true}
attachments.cleanup.cron=${ATTACHMENTS_CLEANUP_CRON:0 0 0/1 * * *}

spring.datasource.url=jdbc:postgresql://${DB_SERVER}:${DB_PORT}/websocket_chat_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=30MB

websocket-chat.hostname=${HOSTNAME}
encryption.message.secret=${ENCRYPTION_MESSAGE_SECRET:WebSocketChatSecret@2025}
jwt.secret=${JWT_SECRET:11379da7ecdb576f0037deefa005620be3a1daee88e36db1a83400b13f71ad7c}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.aws.s3.bucket-name=${S3_BUCKET_NAME:websocket-chat-files}
app.aws.s3.region=${AWS_REGION:eu-central-1}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG